name: Baqend
on:
  push:
    branches:
      - master
      - feature/*

jobs:
  install:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Install
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: cache node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

  build-baqend-pages:
    name: Build (Baqend-Pages)
    needs: install
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: cache node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
      - name: Build
        run: |
          npm run generate --base=/${GITHUB_REF##refs/heads/}/ --website-host=https://pagespeed.app.baqend.com/${GITHUB_REF##refs/heads/}
          mkdir dist/reports dist/reports/webpack
          cp -R .reports/webpack/* dist/reports/webpack
          touch dist/.nojekyll
        env:
          DIST_PATH: dist
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: baqendpages
          path: dist

  deploy-baqend:
    name: Deploy (Baqend-Pages)
    needs: build-baqend-pages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: baqendpages
          path: baqendpages
      - name: Deploy to Baqend
        run: npx baqend deploy -f baqendpages -b www/${GITHUB_REF##refs/heads/} pagespeed
        env:
          BAQEND_TOKEN: ${{ secrets.BAQEND_TOKEN }}
